### ISSUE TITLE
An example code with how to use this repo would be great.

### ISSUE THREAD

**Issue by infinite-Joy** [linkfluence/fastText4j#2]
This library looks amazing but I have not been able to use it as my java is sketchy at best. Please add some example code on how to use this repo.

I want to see if I can use this repo in a sample android app.

**Comment by JadeCopet** [comment]
Hello, 

I added a tutorial file to provide an example on how you can use the lib. You can also have a look at the documentation comments available on the functions in FastText.java that detail the methods you can use with your model. I hope it will help !

**Comment by ali3assi** [comment]
@JadeCopet please can you confirm wich type format of file can we use from  (https://fasttext.cc/docs/en/pretrained-vectors.html)? in my code i use wiki.en.bin and i get the following exception:

Oops something went wrong. Exception: Model file has wrong file format
 In addition your fasttext version support the OOV?
